concepts:
  - name: product
    fields:
      - type: identifying name
      - name: type
        type: enum
        values:
           - hottub
           - sauna
           - tiny house
      - type: unitprice
        constraints:
          - cents: false
          - currency: EUR
      - type: product properties
      - type: product options
        constraints:
          - for: unitprice
            cents: false
            currency: EUR